// Generates lib/us-map-paths.ts — static SVG path data for every US state and
// territory, projected once at build time.
//
// Run when the map needs regenerating, NOT on every build:
//   pnpm --filter civica-web add -D us-atlas topojson-client d3-geo
//   node scripts/gen-us-map.mjs
//   pnpm --filter civica-web remove us-atlas topojson-client d3-geo
//
// Same pattern as the self-hosted fonts: the tooling produces a committed
// artifact and is then removed, so the build needs nothing but the repo and the
// browser ships no projection library.
//
// geoAlbersUsa on purpose — it insets Alaska and Hawaii at readable sizes
// instead of putting Alaska across the top of the world.

import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { feature } from "topojson-client";
import { geoAlbersUsa, geoPath } from "d3-geo";

const require = createRequire(import.meta.url);
const topo = require("us-atlas/states-10m.json");

// FIPS is what us-atlas keys on; the product speaks USPS codes everywhere else.
// Mapped by NAME rather than by memorising 56 FIPS numbers — a wrong name is
// obvious on sight, a wrong FIPS is not.
const CODE_BY_NAME = {
  Alabama: "AL", Alaska: "AK", Arizona: "AZ", Arkansas: "AR", California: "CA",
  Colorado: "CO", Connecticut: "CT", Delaware: "DE", "District of Columbia": "DC",
  Florida: "FL", Georgia: "GA", Hawaii: "HI", Idaho: "ID", Illinois: "IL",
  Indiana: "IN", Iowa: "IA", Kansas: "KS", Kentucky: "KY", Louisiana: "LA",
  Maine: "ME", Maryland: "MD", Massachusetts: "MA", Michigan: "MI",
  Minnesota: "MN", Mississippi: "MS", Missouri: "MO", Montana: "MT",
  Nebraska: "NE", Nevada: "NV", "New Hampshire": "NH", "New Jersey": "NJ",
  "New Mexico": "NM", "New York": "NY", "North Carolina": "NC",
  "North Dakota": "ND", Ohio: "OH", Oklahoma: "OK", Oregon: "OR",
  Pennsylvania: "PA", "Rhode Island": "RI", "South Carolina": "SC",
  "South Dakota": "SD", Tennessee: "TN", Texas: "TX", Utah: "UT",
  Vermont: "VT", Virginia: "VA", Washington: "WA", "West Virginia": "WV",
  Wisconsin: "WI", Wyoming: "WY",
};

const WIDTH = 960;
const HEIGHT = 600;

const states = feature(topo, topo.objects.states);
const projection = geoAlbersUsa().fitSize([WIDTH, HEIGHT], states);
// INTEGER coordinates. The map renders around 700px wide against a 960 viewBox,
// so one unit is ~0.73px and rounding is sub-pixel — invisible. It halves the
// payload: 55KB gzipped at one decimal, 28KB at zero.
const path = geoPath(projection).digits(0);

const out = {};
const skipped = [];
for (const f of states.features) {
  const code = CODE_BY_NAME[f.properties.name];
  if (!code) {
    // Territories are in the topology but geoAlbersUsa does not project them,
    // so they would silently render as empty paths. Named here rather than
    // dropped in silence.
    skipped.push(f.properties.name);
    continue;
  }
  const d = path(f);
  if (d) out[code] = d;
  else skipped.push(`${f.properties.name} (not projected)`);
}

const body = `// GENERATED by scripts/gen-us-map.mjs — do not edit by hand.
//
// Albers USA projection, viewBox 0 0 ${WIDTH} ${HEIGHT}, coordinates rounded to
// one decimal. Alaska and Hawaii are inset by the projection.
//
// NOT INCLUDED: ${skipped.join(", ") || "none"}.
// geoAlbersUsa deliberately projects only the 50 states and DC; the territories
// have their own place in the picker and the NAP hand-off, not on this map.

export const US_MAP_VIEWBOX = "0 0 ${WIDTH} ${HEIGHT}";

export const US_STATE_PATHS: Record<string, string> = ${JSON.stringify(out, null, 0)};
`;

writeFileSync(new URL("../lib/us-map-paths.ts", import.meta.url), body);
console.log(`wrote ${Object.keys(out).length} paths; skipped: ${skipped.join(", ") || "none"}`);
