// Net-new: SNAP readiness packet CRUD (no Flask equivalent).
import { Hono } from "hono";
import { requireAuth } from "../../middleware/auth.js";
import { prisma } from "@civica/db";
import { CreatePacketInputSchema, UploadDocumentInputSchema } from "@civica/types";

type AuthEnv = { Variables: { userId: string } };
export const packetsRouter = new Hono<AuthEnv>();

// List packets for the authenticated user
packetsRouter.get("/api/v1/snap/packets", requireAuth, async (c) => {
  const userId = c.get("userId");
  const packets = await prisma.packet.findMany({
    where: { user_id: userId },
    include: { documents: true },
    orderBy: { created_at: "desc" },
  });
  return c.json({ data: packets });
});

// Create a new packet
packetsRouter.post("/api/v1/snap/packets", requireAuth, async (c) => {
  const userId = c.get("userId");
  const body = CreatePacketInputSchema.parse(await c.req.json());
  const packet = await prisma.packet.create({
    data: { user_id: userId, state: body.state, status: "draft" },
  });
  return c.json(packet, 201);
});

// Get a single packet
packetsRouter.get("/api/v1/snap/packets/:id", requireAuth, async (c) => {
  const userId = c.get("userId");
  const packet = await prisma.packet.findFirst({
    where: { id: c.req.param("id"), user_id: userId },
    include: { documents: { include: { extraction_fields: true } } },
  });
  if (!packet) return c.json({ code: "not_found", message: "Packet not found" }, 404);
  return c.json(packet);
});

// Request a signed upload URL for a document
packetsRouter.post("/api/v1/snap/packets/:id/documents/upload-url", requireAuth, async (c) => {
  const userId = c.get("userId");
  const packetId = c.req.param("id");

  const packet = await prisma.packet.findFirst({ where: { id: packetId, user_id: userId } });
  if (!packet) return c.json({ code: "not_found", message: "Packet not found" }, 404);

  const body = UploadDocumentInputSchema.omit({ packet_id: true }).parse(await c.req.json());
  const storagePath = `documents/${crypto.randomUUID()}/${body.file_name}`;

  const document = await prisma.document.create({
    data: {
      packet_id: packetId,
      type: body.type,
      status: "pending",
      storage_path: storagePath,
      file_name: body.file_name,
      file_size_bytes: body.file_size_bytes,
      mime_type: body.mime_type,
    },
  });

  // Signed URL is generated by Supabase Storage — the client uploads directly.
  // The API returns the path; the frontend calls Supabase SDK createSignedUploadUrl.
  const expiresAt = new Date(Date.now() + 15 * 60 * 1000).toISOString();
  return c.json(
    { document_id: document.id, storage_path: storagePath, expires_at: expiresAt },
    201,
  );
});
