// The one link-preview image, generated by app/opengraph-image.tsx and served
// at /opengraph-image.
//
// WHY THIS EXISTS. The file-convention opengraph-image applies to "/" only, and
// "/" 301s to /screen/ask — so the image never reached the page a shared link
// actually lands on. Routes that set their own `openGraph` (screen/ask and its
// localized siblings) reference this explicitly so the rich card comes back
// (launch audit 2026-08-29). English-only for now; a localized card is a later
// enhancement — an English image still beats no image.
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "Demeter AI. See if you qualify for SNAP food benefits, with verified answers for any state",
} as const;
