// The exported case-file PDF (mockup frame 07). Org members only — a
// guest's Export PDF button stays disabled (enforced both client-side in
// ScreeningWorksheet and server-side in the export route, which requires
// an org identity). Content mirrors ScreeningWorksheet.tsx exactly via the
// shared screening-worksheet-shape module — this is a second RENDERING of
// the same data, not a second source of truth for what that data means.

import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { OUTCOME_COPY, CALC_ROWS, money, type BenefitCalcDetail } from "./screening-worksheet-shape";

const TERRACOTTA = "#C0553B";
const INK = "#2A211C";
const BODY = "#5E4F45";
const MONO = "#8A7666";
const BORDER = "#E5D9C9";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10.5, color: INK, fontFamily: "Helvetica" },
  eyebrow: { fontSize: 9, color: MONO, letterSpacing: 1, textTransform: "uppercase", marginBottom: 2 },
  title: { fontSize: 20, fontWeight: 700, marginBottom: 2 },
  meta: { fontSize: 9.5, color: MONO, marginBottom: 20 },
  section: { marginBottom: 18, paddingBottom: 14, borderBottom: `1pt solid ${BORDER}` },
  sectionTitle: { fontSize: 10, fontWeight: 700, textTransform: "uppercase", letterSpacing: 0.5, color: BODY, marginBottom: 8 },
  resultLabel: { fontSize: 16, fontWeight: 700, color: TERRACOTTA, marginBottom: 4 },
  resultSummary: { fontSize: 10.5, color: BODY, lineHeight: 1.5 },
  benefitLine: { fontSize: 12, fontWeight: 700, marginTop: 8 },
  row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 4 },
  rowLabel: { color: BODY },
  rowValue: { fontWeight: 700 },
  listItem: { fontSize: 10, color: BODY, marginBottom: 4 },
  disclaimer: { fontSize: 8.5, color: MONO, marginTop: 20, lineHeight: 1.5 },
});

export interface ScreeningPdfProps {
  caseLabel: string | null;
  orgName: string;
  stateCode: string;
  generatedAt: string;
  outcome: string;
  summary: string;
  calc?: BenefitCalcDetail;
  stillNeeded: string[];
}

export function ScreeningPdfDocument({
  caseLabel,
  orgName,
  stateCode,
  generatedAt,
  outcome,
  summary,
  calc,
  stillNeeded,
}: ScreeningPdfProps) {
  const copy = OUTCOME_COPY[outcome] ?? { label: outcome, tone: "pending" as const };
  const rows = calc ? CALC_ROWS.filter(([k]) => calc[k] !== undefined) : [];

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.eyebrow}>Demeter · Submission file</Text>
        <Text style={styles.title}>{caseLabel ?? "Screening case"}</Text>
        <Text style={styles.meta}>
          {orgName} · {stateCode} policy set · Generated {generatedAt}
        </Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Screening result</Text>
          <Text style={styles.resultLabel}>{copy.label}</Text>
          <Text style={styles.resultSummary}>{summary}</Text>
          {calc && outcome !== "not_enough_information" && (
            <Text style={styles.benefitLine}>Est. monthly benefit: {money(calc.monthly_benefit)}</Text>
          )}
        </View>

        {rows.length > 0 && calc && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Benefit calculation</Text>
            {rows.map(([key, label]) => (
              <View style={styles.row} key={key}>
                <Text style={styles.rowLabel}>{label}</Text>
                <Text style={styles.rowValue}>{money(calc[key])}</Text>
              </View>
            ))}
          </View>
        )}

        {stillNeeded.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Still needed ({stillNeeded.length})</Text>
            {stillNeeded.map((item) => (
              <Text style={styles.listItem} key={item}>
                • {item}
              </Text>
            ))}
          </View>
        )}

        <Text style={styles.disclaimer}>
          Screening estimate only, generated by Demeter. The county agency makes the final SNAP
          eligibility determination based on a complete application and verification.
        </Text>
      </Page>
    </Document>
  );
}
