// GENERATED by scripts/gen-retailer-counts.mjs — do not edit by hand.
//
// SNAP-authorized retailers per state, from USDA's SNAP Retailer Locator
// feature service. 53 jurisdictions, 252,894 stores.
//
// These are STORE COUNTS, not a measure of how easy it is to reach one. A rural
// state with few stores is not necessarily badly served, and a dense one is not
// necessarily well served — anything the UI says about this has to stay on the
// right side of that line.
//
// Source: services1.arcgis.com/.../snap_retailer_location_data/FeatureServer/0

export const RETAILERS_AS_OF = "2026-08-12";
export const RETAILER_TOTAL = 252894;
export const RETAILERS_BY_STATE: Record<string, number> = {"AK":496,"AL":4867,"AR":2508,"AZ":4713,"CA":30180,"CO":3149,"CT":2375,"DC":404,"DE":744,"FL":14236,"GA":9265,"GU":237,"HI":864,"IA":2895,"ID":1083,"IL":9075,"IN":5406,"KS":2065,"KY":4458,"LA":4063,"MA":5302,"MD":3753,"ME":1370,"MI":9531,"MN":3558,"MO":4936,"MS":2928,"MT":759,"NC":8942,"ND":548,"NE":1400,"NH":987,"NJ":5359,"NM":1627,"NV":1988,"NY":16754,"OH":9490,"OK":3756,"OR":3314,"PA":9727,"RI":889,"SC":5039,"SD":778,"TN":6388,"TX":20829,"UT":1533,"VA":6081,"VI":93,"VT":628,"WA":4860,"WI":4277,"WV":1990,"WY":397};
