// ---------------------------------------------------------------------------
// POST /v1/intake/help — Tier B universal contextual-help explainer.
//
// Monday 2026-06-01 TestFlight demo path (per design doc
// matthewgreer-gentis-claude-dashboard-state-coverage-design-20260529-135546.md).
// The shared SwiftUI question screen renders a `questionmark.circle` button on
// every intake question. Tapping it opens a sheet that POSTs here with the
// question title + locale; we return a plain-language explainer generated by
// Claude Sonnet 4.6, grounded in CDSS + 7 CFR 273 + packages/snap-rules +
// SNAPAgencyDirectory.
//
// IMPORTANT (Tier B fallback rigor, per founder's #1 demo fear):
// The LLM MUST NEVER refuse ("sorry, I can't help"). The system prompt
// instructs it to either (a) explain what the question is asking, or
// (b) give a partial explanation + a navigator nudge. A refusal kills the
// demo's universal-coverage thesis.
//
// IMPORTANT (Hard safety rule):
// The AI EXPLAINS questions; it NEVER COMMITS to eligibility outcomes. A
// two-layer safety filter enforces this:
//   1. Prompt-level: the system prompt's 6 hard rules ban eligibility
//      commitments and prescriptive instructions.
//   2. Post-generation: a regex pass over the model output catches forbidden
//      phrases in EN/ES. On match, the response is replaced with
//      SAFE_FALLBACK, `was_filtered` is set true, and a structured violation
//      event is console.log'd for post-demo review.
//
// Auth: anonymous via `x-anonymous-id` header (NO Supabase JWT). This route
// mounts BEFORE the authed /v1/enrollment subtree, mirroring the
// /v1/enrollment/feature-flags + /v1/enrollment/oauth/device pattern.
//
// Rate limit: strict tier (10/min per anonymous-id) via lib/rate-limit.ts.
// We synthesize an actor row from the header so the existing bucketKey()
// helper keys per-anonymous-id instead of collapsing all callers into a
// shared IP bucket.
// ---------------------------------------------------------------------------

import { Hono } from "hono";
import { zValidator } from "@hono/zod-validator";
import { z } from "zod";
import { HTTPException } from "hono/http-exception";
import type { Context, Next } from "hono";
import { rateLimit } from "../lib/rate-limit.js";
import type { Env, Actor } from "../types.js";

const app = new Hono<{ Bindings: Env }>();

const MODEL = "claude-sonnet-4-6";
const MAX_TITLE_CHARS = 240;
const MAX_TOKENS = 360;
const REQUEST_TIMEOUT_MS = 15_000;

// ---------------------------------------------------------------------------
// Request / response schemas
// ---------------------------------------------------------------------------

const helpRequestSchema = z.object({
  question_title: z.string().min(1).max(MAX_TITLE_CHARS),
  locale: z.enum(["en", "es"]),
});

type HelpResponse = {
  explainer_text: string;
  was_filtered: boolean;
};

// ---------------------------------------------------------------------------
// Tier B system prompt — 6 numbered hard rules (per design doc D3).
//
// Rules are numbered so violations can be greppable in server logs. RAG
// grounding is listed; the model is told to fall back to navigator language
// rather than refuse.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// CA reference guidance — hand-authored by Civica for the existing Interview
// Coach product. Copied here from
// Civica/Features/SNAP/InterviewCoach/InterviewQuestions_CA.json so the LLM
// can use it as background when the applicant's question relates to one of
// these CA-specific topics (household, income, gig, expenses, student,
// immigration, identity, expedited, change reporting). The LLM still
// generates the explainer; the corpus primes it with Civica's voice on the
// topics that matter most for the CA launch.
//
// Update path: when InterviewQuestions_CA.json changes upstream, mirror the
// edits here. v1.1 will centralize via a build-time JSON import; for v1 we
// inline to keep the Worker deploy unit small and the prompt review easy.
// ---------------------------------------------------------------------------

const CA_REFERENCE_GUIDANCE = [
  "REFERENCE KNOWLEDGE — Civica's curated guidance for common CA SNAP topics. Use as background when the applicant's question relates to one of these. Do not quote verbatim. Adapt to the explainer format above. Do not list citations.",
  "",
  "[1] Household composition / who shares food costs",
  "A CalFresh household is everyone who buys and prepares food together — not necessarily everyone on the lease. Roommates who shop and cook separately are different households even if they share a kitchen. The frame: who shares food, not who shares an address.",
  "",
  "[2] Gross monthly income",
  "Gross means pre-tax earnings from all sources for everyone in the CalFresh household. If income varies week to week, a recent four-week average is acceptable. Do not estimate downward — the county verifies with pay stubs, and mismatches delay or deny benefits.",
  "",
  "[3] Gig / self-employment income",
  "Report gross self-employment income; allowable business expenses reduce the net amount used for CalFresh. Platform drivers (Uber, DoorDash, Instacart): mileage, platform fees, and gas count as expenses. CalFresh allows actual expenses OR a flat 40% deduction. A recent earnings summary from the platform is a helpful document to bring.",
  "",
  "[4] Rent, utilities, and housing costs",
  "Include rent or mortgage plus separate amounts for heat, electricity, gas, water, trash, phone, and internet. California grants the Standard Utility Allowance (SUA) when a heat or cooling bill is paid separately from rent — usually the higher deduction, so the applicant should mention any utility bill in their name.",
  "",
  "[5] Student work-requirement exemption",
  "Half-time students 18-49 are typically not eligible for CalFresh without an exemption. Common exemptions: working 20+ hours per week, caring for a dependent under 12, enrolled in EOPS/CARE/CalWORKs, enrolled in a Local Program That Increases Employability (LPTIE — many CA community colleges qualify), or receiving certain disability benefits.",
  "",
  "[6] Immigration / mixed-status households",
  "Only applying members need to disclose immigration status. Members not applying do not need to. Children born in the US are citizens regardless of parent status. Non-citizens who do not qualify for federal CalFresh may qualify for the California Food Assistance Program (CFAP) — same benefit, state-funded. When unsure, a CalFresh outreach worker can help clarify before answering.",
  "",
  "[7] Identity verification documents",
  "Acceptable CA ID includes state ID, driver license or AB 60 license, passport, Matrícula Consular, work or school ID, voter card, or two of: birth certificate, social security card, hospital records. If no ID is available at interview, federal rules require the county to accept a sworn statement plus a collateral contact (someone who can vouch for the applicant).",
  "",
  "[8] Expedited (three-day) CalFresh",
  "Expedited service requires household resources under $100 plus gross income under $150 for the month, OR rent and utilities exceeding combined income and resources. If the interview is completed at intake, same-day benefits are sometimes possible.",
  "",
  "[9] Reporting changes in household",
  "Report every change in who shares food costs, not just lease changes. Even temporary changes (sibling staying a month) should be mentioned if they affect food sharing. In California, changes can be reported via BenefitsCal.com, by phone, or in person at the county office.",
].join("\n");

const TIER_B_SYSTEM_PROMPT_EN = [
  "You are Civica's SNAP application assistant. An applicant has tapped a help button next to a specific question on a 17+ page CalFresh (California SNAP) intake form. Your job is to explain what the question is asking in plain, friendly, 6th-grade English so the applicant can answer with confidence.",
  "",
  "Hard rules (numbered for compliance):",
  "1. NEVER REFUSE. You always have something useful to say. If the question is unfamiliar, explain it in general terms and add 'Your county navigator can clarify the exact answer for your situation.' Refusing to help is the single worst thing you can do here.",
  "2. NEVER commit to eligibility outcomes. Do not say 'you qualify,' 'you don't qualify,' 'you are eligible,' 'you are ineligible,' or 'you should report this.' You explain; the county decides.",
  "3. Fall back to navigator language whenever you are uncertain about a specific rule. Phrases like 'a county navigator can confirm the exact rule for your case' are encouraged.",
  "4. Plain 6th-grade English. Short sentences. No legal jargon (avoid 'gross income threshold,' 'BBCE,' 'ABAWD'). If a SNAP term is required, define it inline in one short clause.",
  "5. Locale-aware. The applicant's locale is English. Respond in English only. Do not switch languages mid-response.",
  "6. RAG grounding (informational only, not a citation list to the applicant): your background knowledge of CDSS guidance, 7 CFR 273, packages/snap-rules canonical rule data, and SNAPAgencyDirectory state-conditioned copy informs your explanation. The applicant never sees citations; they see a clean explanation.",
  "",
  "Format: 2-5 short sentences. No bullet points unless the question is genuinely a list. No headers. No greeting or sign-off. Just the explanation.",
  "",
  CA_REFERENCE_GUIDANCE,
].join("\n");

const TIER_B_SYSTEM_PROMPT_ES = [
  "Eres el asistente de solicitud de SNAP de Civica. Un solicitante tocó un botón de ayuda junto a una pregunta específica en un formulario de admisión de CalFresh (SNAP de California) de más de 17 páginas. Tu trabajo es explicar qué está preguntando la pregunta en español sencillo y amigable, a nivel de sexto grado, para que el solicitante pueda responder con confianza.",
  "",
  "Reglas estrictas (numeradas para cumplimiento):",
  "1. NUNCA TE NIEGUES. Siempre tienes algo útil que decir. Si la pregunta no es familiar, explícala en términos generales y agrega 'El orientador de su condado puede aclarar la respuesta exacta para su situación.' Negarse a ayudar es lo peor que puedes hacer aquí.",
  "2. NUNCA confirmes resultados de elegibilidad. No digas 'usted califica,' 'usted no califica,' 'usted es elegible,' 'usted no es elegible,' ni 'usted debe reportar esto.' Tú explicas; el condado decide.",
  "3. Usa lenguaje de orientador siempre que tengas dudas sobre una regla específica. Frases como 'un orientador del condado puede confirmar la regla exacta para su caso' son recomendadas.",
  "4. Español sencillo de sexto grado. Oraciones cortas. Sin jerga legal (evita 'umbral de ingreso bruto,' 'BBCE,' 'ABAWD'). Si un término de SNAP es necesario, defínelo en una frase corta.",
  "5. Consciente del idioma. El idioma del solicitante es español. Responde solo en español. No cambies de idioma a mitad de respuesta.",
  "6. Fuentes de fundamentación (solo informativas, no es una lista de citas para el solicitante): tu conocimiento de fondo sobre la guía del CDSS, 7 CFR 273, los datos canónicos de packages/snap-rules y SNAPAgencyDirectory con copy condicionado por estado informa tu explicación. El solicitante nunca ve citas; ve una explicación clara.",
  "",
  "Formato: 2-5 oraciones cortas. Sin viñetas a menos que la pregunta sea genuinamente una lista. Sin encabezados. Sin saludo ni despedida. Solo la explicación.",
  "",
  "REFERENCIA — Civica mantiene la guía siguiente en inglés para los temas clave de CalFresh CA. Úsala como conocimiento de fondo cuando la pregunta del solicitante se relacione con uno de estos temas. Traduce los conceptos al español al responder. No cites textualmente. No incluyas lista de fuentes.",
  "",
  CA_REFERENCE_GUIDANCE,
].join("\n");

// ---------------------------------------------------------------------------
// Two-layer safety filter (per design doc D4).
//
// Layer 1 is in the system prompt above (rules 1, 2, 3). Layer 2 is this
// post-generation regex pass. Phrases are matched case-insensitively. On
// any match we replace the entire response with SAFE_FALLBACK and log the
// violation server-side.
//
// The forbidden phrase lists are conservative. False positives are OK
// (SAFE_FALLBACK is still a useful, non-refusing response). False negatives
// kill the demo.
// ---------------------------------------------------------------------------

const FORBIDDEN_PHRASES_EN: RegExp[] = [
  /\byou\s+(do\s+)?qualify\b/i,
  /\byou\s+(do\s+)?(not|don'?t)\s+qualify\b/i,
  /\byou\s+(are|'re)\s+eligible\b/i,
  /\byou\s+(are|'re)\s+not\s+eligible\b/i,
  /\byou\s+(are|'re)\s+ineligible\b/i,
  /\byou\s+should\s+report\b/i,
  /\byou\s+(must|need\s+to)\s+report\b/i,
  /\byou\s+should\s+(select|choose|pick|answer|say)\b/i,
  /\byou\s+(must|need\s+to)\s+(select|choose|pick|answer|say)\b/i,
  /\byou\s+will\s+(be\s+)?(approved|denied)\b/i,
  /\byou\s+(will\s+)?get\s+(approved|denied)\b/i,
  /\bbenefits?\s+will\s+be\s+(approved|denied)\b/i,
];

const FORBIDDEN_PHRASES_ES: RegExp[] = [
  /\busted\s+califica\b/i,
  /\busted\s+no\s+califica\b/i,
  /\busted\s+es\s+elegible\b/i,
  /\busted\s+no\s+es\s+elegible\b/i,
  /\busted\s+debe\s+reportar\b/i,
  /\busted\s+tiene\s+que\s+reportar\b/i,
  /\busted\s+debe\s+(seleccionar|elegir|responder|decir)\b/i,
  /\busted\s+tiene\s+que\s+(seleccionar|elegir|responder|decir)\b/i,
  /\busted\s+ser[aá]\s+(aprobado|negado|denegado)\b/i,
  /\bsus\s+beneficios?\s+ser[aá]n?\s+(aprobado|negado|denegado)s?\b/i,
];

const SAFE_FALLBACK_EN =
  "This question is asking for specific information about your situation. We don't want to guess and give you the wrong answer, so your county navigator can walk you through it. You can also call 2-1-1 for free help filling out the application.";

const SAFE_FALLBACK_ES =
  "Esta pregunta pide información específica sobre su situación. No queremos adivinar y darle la respuesta incorrecta, así que un orientador del condado puede guiarlo. También puede llamar al 2-1-1 para obtener ayuda gratuita para completar la solicitud.";

/**
 * Apply the post-generation safety filter. Returns the cleaned text and
 * whether a forbidden phrase was matched. On match, the original response
 * and matched pattern are logged server-side for post-demo review.
 */
function applySafetyFilter(
  rawText: string,
  locale: "en" | "es",
  context: { question_title: string; anonymous_id: string | null },
): { text: string; was_filtered: boolean } {
  const phrases = locale === "es" ? FORBIDDEN_PHRASES_ES : FORBIDDEN_PHRASES_EN;
  for (const pattern of phrases) {
    if (pattern.test(rawText)) {
      // Structured violation event — greppable in server logs.
      // We log the original response + matched pattern so an operator can
      // tighten the system prompt post-demo without losing the trigger.
      console.log(
        JSON.stringify({
          level: "warn",
          msg: "intake_help_safety_filter_triggered",
          route: "POST /v1/intake/help",
          locale,
          matched_pattern: pattern.source,
          question_title: context.question_title.slice(0, 200),
          anonymous_id: context.anonymous_id,
          original_response: rawText.slice(0, 1000),
          ts: new Date().toISOString(),
        }),
      );
      return {
        text: locale === "es" ? SAFE_FALLBACK_ES : SAFE_FALLBACK_EN,
        was_filtered: true,
      };
    }
  }
  return { text: rawText, was_filtered: false };
}

// ---------------------------------------------------------------------------
// Anonymous-id bucket middleware.
//
// Synthesizes a per-request actor row keyed by the x-anonymous-id header so
// the shared rateLimit("strict") middleware keys its bucket per anonymous
// caller rather than collapsing every anonymous caller into a shared IP
// bucket. The actor `kind` is "applicant" — closest match in the existing
// ActorKind union — but the route never reads it back.
// ---------------------------------------------------------------------------

async function requireAnonymousId(c: Context<{ Bindings: Env }>, next: Next): Promise<void> {
  const anonymousId = c.req.header("x-anonymous-id")?.trim();
  if (!anonymousId) {
    throw new HTTPException(400, { message: "Missing x-anonymous-id header" });
  }
  // Stash a synthetic actor so rateLimit("strict") keys per-anonymous-id.
  const synthetic: Actor = { kind: "applicant", id: `anon:${anonymousId}` };
  c.set("actor", synthetic);
  await next();
}

// ---------------------------------------------------------------------------
// Anthropic invocation (native fetch, no npm SDK).
//
// The Workers runtime doesn't support Deno-style npm: imports, and adding
// @anthropic-ai/sdk to package.json bloats the cold start for one call.
// We use the same native-fetch pattern as packages/recert-engine/src/
// interview/scorer.ts so this stays consistent with the rest of the codebase.
// ---------------------------------------------------------------------------

type AnthropicContentBlock =
  | { type: "text"; text: string }
  | { type: "tool_use"; id: string; name: string; input: unknown };

type AnthropicResponse = {
  content?: AnthropicContentBlock[];
};

export type FetchImpl = typeof fetch;

async function callAnthropic(
  apiKey: string,
  systemPrompt: string,
  questionTitle: string,
  fetchImpl: FetchImpl = fetch,
): Promise<string> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);

  try {
    const response = await fetchImpl("https://api.anthropic.com/v1/messages", {
      method: "POST",
      signal: controller.signal,
      headers: {
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
      },
      body: JSON.stringify({
        model: MODEL,
        max_tokens: MAX_TOKENS,
        temperature: 0.3,
        system: systemPrompt,
        messages: [
          {
            role: "user",
            content: `The applicant tapped the help button next to this question:\n\n"${questionTitle}"\n\nExplain what this question is asking in 2-5 short sentences.`,
          },
        ],
      }),
    });

    if (!response.ok) {
      const body = await response.text().catch(() => "");
      throw new Error(`Anthropic API error ${response.status}: ${body.slice(0, 500)}`);
    }

    const data = (await response.json()) as AnthropicResponse;
    const textBlock = data.content?.find(
      (b): b is Extract<AnthropicContentBlock, { type: "text" }> => b.type === "text",
    );
    if (!textBlock || typeof textBlock.text !== "string" || textBlock.text.trim().length === 0) {
      throw new Error("Anthropic response missing text content");
    }
    return textBlock.text.trim();
  } finally {
    clearTimeout(timeout);
  }
}

// Test-only seam: lets the vitest suite swap in a mock fetch without
// monkey-patching globalThis. Production callers go through the default fetch.
let _fetchOverride: FetchImpl | null = null;
export function __setFetchForTests(impl: FetchImpl | null): void {
  _fetchOverride = impl;
}

// ---------------------------------------------------------------------------
// POST /v1/intake/help
// ---------------------------------------------------------------------------

app.post(
  "/",
  requireAnonymousId,
  rateLimit("strict"),
  zValidator("json", helpRequestSchema),
  async (c) => {
    const { question_title, locale } = c.req.valid("json");

    const apiKey = c.env.ANTHROPIC_API_KEY;
    if (!apiKey) {
      throw new HTTPException(500, { message: "ANTHROPIC_API_KEY is not configured" });
    }

    const systemPrompt = locale === "es" ? TIER_B_SYSTEM_PROMPT_ES : TIER_B_SYSTEM_PROMPT_EN;
    const fetchImpl = _fetchOverride ?? fetch;

    let rawText: string;
    try {
      rawText = await callAnthropic(apiKey, systemPrompt, question_title, fetchImpl);
    } catch (err) {
      const message = err instanceof Error ? err.message : "Anthropic call failed";
      // Log the failure server-side; surface a 500 so the iOS sheet can show
      // its error state (echo of question_title + navigator nudge per D6).
      console.log(
        JSON.stringify({
          level: "error",
          msg: "intake_help_llm_failure",
          route: "POST /v1/intake/help",
          locale,
          error: message,
          question_title: question_title.slice(0, 200),
          ts: new Date().toISOString(),
        }),
      );
      throw new HTTPException(500, { message: "LLM generation failed" });
    }

    const anonymousId = c.req.header("x-anonymous-id")?.trim() ?? null;
    const filtered = applySafetyFilter(rawText, locale, {
      question_title,
      anonymous_id: anonymousId,
    });

    const body: HelpResponse = {
      explainer_text: filtered.text,
      was_filtered: filtered.was_filtered,
    };
    return c.json(body);
  },
);

export default app;

// ---------------------------------------------------------------------------
// Test-only exports
// ---------------------------------------------------------------------------

export const __testing = {
  applySafetyFilter,
  TIER_B_SYSTEM_PROMPT_EN,
  TIER_B_SYSTEM_PROMPT_ES,
  SAFE_FALLBACK_EN,
  SAFE_FALLBACK_ES,
  FORBIDDEN_PHRASES_EN,
  FORBIDDEN_PHRASES_ES,
};
