import Foundation
import OSLog

/// Source of fallback location data. Lets `FindHelpStore` swap in a
/// synthetic provider in tests; production always uses the bundled
/// JSON via `FindHelpFixtureLoader`.
protocol FindHelpFallbackProviding {
    func fallbackResults(
        lat: Double,
        lng: Double,
        radiusKm: Double,
        serviceType: FindHelpServiceType?,
        languageCode: String?,
        maxResults: Int
    ) -> [FindHelpLocation]
}

/// Loads the bundled regional fixtures and exposes a search API that
/// mirrors what the live Supabase RPC returns. Used by FindHelpStore
/// as a soft fallback when the live RPC fails or returns an empty
/// response so the map is never blank.
struct FindHelpFixtureLoader: FindHelpFallbackProviding {
    static let shared = FindHelpFixtureLoader(bundle: .main)

    private let bundle: Bundle
    private static let logger = Logger(subsystem: "Civica", category: "FindHelpFixtures")

    init(bundle: Bundle) {
        self.bundle = bundle
    }

    /// Returns locations within `radiusKm` of the given coordinate,
    /// after applying the same service-type / language filters the
    /// live RPC would, sorted by distance ascending and capped at
    /// `maxResults`. The returned objects' `distanceKm` is populated
    /// so the list view shows the same "X.X mi away" rows it would
    /// from a live response.
    func fallbackResults(
        lat: Double,
        lng: Double,
        radiusKm: Double,
        serviceType: FindHelpServiceType?,
        languageCode: String?,
        maxResults: Int
    ) -> [FindHelpLocation] {
        // No region bbox gate here — the haversine distance filter is
        // sufficient. A CA user will never be within `radiusKm` of an
        // MA fixture row, and vice versa. Removing the region check
        // means this fallback works correctly regardless of which
        // FindHelpDemoRegion is set in Info.plist.
        let withDistance: [FindHelpLocation] = loadAll().compactMap { location in
            guard let locLat = location.latitude, let locLng = location.longitude else { return nil }
            let distance = haversineKm(lat1: lat, lng1: lng, lat2: locLat, lng2: locLng)
            guard distance <= radiusKm else { return nil }
            if let serviceType, !matches(location, serviceType: serviceType) { return nil }
            if let languageCode, !(location.languagesJson ?? []).contains(languageCode) { return nil }
            var withDistance = location
            withDistance.distanceKm = distance
            return withDistance
        }
        return Array(withDistance.sorted { ($0.distanceKm ?? .infinity) < ($1.distanceKm ?? .infinity) }.prefix(maxResults))
    }

    /// All bundled locations, unfiltered. Empty array on decode
    /// failure (logged). Exposed for tests / introspection.
    ///
    /// Resource selection follows `FindHelpRegion.current`: each region
    /// has its own bundled fixture file (MA ships a hand-curated mix of
    /// help-directory + retailer rows; CA ships a USDA-derived retailer
    /// snapshot generated by `scripts/build_retailer_fixture.py`).
    /// Missing files are tolerated so a partial bundle still boots.
    ///
    /// Decoded results are cached per resource — the CA retailer fixture
    /// alone is ~24k rows / ~485k JSON lines; re-decoding on every fallback
    /// fire (which happens on every CoreLocation update past the dedupe
    /// threshold, every filter change, every "Search this area" tap)
    /// would burn hundreds of MB of allocs and hundreds of ms per call.
    func loadAll() -> [FindHelpLocation] {
        let resources = Self.fixtureResources(for: FindHelpRegion.current)
        var combined: [FindHelpLocation] = []
        for resource in resources {
            combined.append(contentsOf: Self.cachedLocations(for: resource, bundle: bundle))
        }
        return combined
    }

    private static let cacheLock = NSLock()
    nonisolated(unsafe) private static var locationCache: [String: [FindHelpLocation]] = [:]
    private static let decoder = JSONDecoder()

    private static func cachedLocations(for resource: String, bundle: Bundle) -> [FindHelpLocation] {
        cacheLock.lock()
        defer { cacheLock.unlock() }
        if let cached = locationCache[resource] { return cached }
        guard let url = bundle.url(forResource: resource, withExtension: "json") else {
            logger.error("FindHelp fixture missing: \(resource, privacy: .public)")
            locationCache[resource] = []
            return []
        }
        do {
            let data = try Data(contentsOf: url)
            let envelope = try decoder.decode(Envelope.self, from: data)
            locationCache[resource] = envelope.locations
            return envelope.locations
        } catch {
            logger.error("FindHelp fixture \(resource, privacy: .public) decode failed: \(error.localizedDescription, privacy: .public)")
            locationCache[resource] = []
            return []
        }
    }

    private static func fixtureResources(for region: FindHelpRegion) -> [String] {
        // Always load every bundled fixture. The fallback path is the
        // primary consumer and it relies on the haversine distance
        // filter to pick the closest results — gating by region here
        // would strand a user in a non-active region (e.g. an MA tester
        // when FindHelpDemoRegion=california) on a blank map. Missing
        // files are tolerated below so this is safe to over-include.
        return ["ma_seed_locations", "ma_retailers", "ca_retailers"]
    }

    // MARK: - Filter parity with FindHelpFilterState.matches

    private func matches(_ location: FindHelpLocation, serviceType: FindHelpServiceType) -> Bool {
        switch serviceType {
        case .both:
            let types = Set(location.serviceTypes)
            return types.contains(.both) || (types.contains(.snapApplicationHelp) && types.contains(.foodAssistance))
        default:
            return location.serviceTypes.contains(serviceType)
        }
    }

    // MARK: - Haversine

    /// Great-circle distance in kilometers. Earth radius 6371 km.
    private func haversineKm(lat1: Double, lng1: Double, lat2: Double, lng2: Double) -> Double {
        let r = 6371.0
        let dLat = (lat2 - lat1) * .pi / 180
        let dLng = (lng2 - lng1) * .pi / 180
        let a = sin(dLat / 2) * sin(dLat / 2)
            + cos(lat1 * .pi / 180) * cos(lat2 * .pi / 180)
            * sin(dLng / 2) * sin(dLng / 2)
        return 2 * r * atan2(sqrt(a), sqrt(1 - a))
    }

    // MARK: - JSON envelope

    private struct Envelope: Decodable {
        let version: Int
        let scope: String
        let locations: [FindHelpLocation]
    }

}

