#!/usr/bin/env python3
from __future__ import annotations

"""Export normalized state legislators JSON payload into runnable SQL.

Input format:
{
  "meta": {...},
  "rows": [ ... ]
}
"""

import argparse
import json
from pathlib import Path
from typing import Any

DEFAULT_INPUT_PATH = Path("data/derived/openstates_state_legislators_current.json")
DEFAULT_OUTPUT_PATH = Path("reports/state_legislators_bootstrap.sql")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export state legislators payload to SQL")
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT_PATH,
        help=f"Input JSON path (default: {DEFAULT_INPUT_PATH})",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help=f"Output SQL path (default: {DEFAULT_OUTPUT_PATH})",
    )
    parser.add_argument(
        "--chunk-size",
        type=int,
        default=300,
        help="Rows per insert statement chunk (default: 300)",
    )
    return parser.parse_args()


def sql_literal(value: Any) -> str:
    if value is None:
        return "NULL"
    raw = str(value)
    return "'" + raw.replace("'", "''") + "'"


def normalize_text(value: Any) -> str | None:
    if value is None:
        return None
    text = " ".join(str(value).split()).strip()
    return text or None


def chunked(items: list[Any], size: int) -> list[list[Any]]:
    return [items[i : i + size] for i in range(0, len(items), size)]


def main() -> None:
    args = parse_args()
    if args.chunk_size <= 0:
        raise ValueError("--chunk-size must be > 0")

    payload = json.loads(args.input.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("Input payload must be a JSON object")

    raw_rows = payload.get("rows")
    if not isinstance(raw_rows, list):
        raise ValueError("Input payload must include a 'rows' array")

    meta = payload.get("meta", {}) if isinstance(payload.get("meta"), dict) else {}
    source_url = normalize_text(meta.get("source_url"))
    source_as_of = normalize_text(meta.get("as_of"))

    rows: list[dict[str, Any]] = []
    states: set[str] = set()
    for raw in raw_rows:
        if not isinstance(raw, dict):
            continue
        state = normalize_text(raw.get("state"))
        if state:
            states.add(state.upper())
        rows.append(
            {
                "legislator_key": normalize_text(raw.get("legislator_key")),
                "source_person_id": normalize_text(raw.get("source_person_id")),
                "seat_key": normalize_text(raw.get("seat_key")),
                "state": state.upper() if state else None,
                "chamber": normalize_text(raw.get("chamber")),
                "district": normalize_text(raw.get("district")),
                "name": normalize_text(raw.get("name")),
                "title": normalize_text(raw.get("title")),
                "party": normalize_text(raw.get("party")),
                "website": normalize_text(raw.get("website")),
                "phone": normalize_text(raw.get("phone")),
                "source_file": normalize_text(raw.get("source_file")),
                "source_snapshot_url": source_url,
                "source_snapshot_as_of": source_as_of,
            }
        )

    if not rows:
        raise ValueError("No rows found in payload.")

    for row in rows:
        required_fields = (
            "legislator_key",
            "source_person_id",
            "seat_key",
            "state",
            "chamber",
            "district",
            "name",
            "title",
        )
        missing = [key for key in required_fields if not row.get(key)]
        if missing:
            raise ValueError(f"Missing required field(s) {missing} for row: {row}")

    states_list = sorted(states)
    quoted_states = ", ".join(sql_literal(code) for code in states_list)

    header = [
        "-- Generated by scripts/export_state_legislators_sql.py",
        f"-- Rows: {len(rows)}",
        f"-- States: {', '.join(states_list)}",
        "begin;",
        "",
        "delete from public.state_legislators_current",
        f"where state in ({quoted_states});",
        "",
    ]

    columns = [
        "legislator_key",
        "source_person_id",
        "seat_key",
        "state",
        "chamber",
        "district",
        "name",
        "title",
        "party",
        "website",
        "phone",
        "source_file",
        "source_snapshot_url",
        "source_snapshot_as_of",
        "last_synced_at",
        "updated_at",
    ]
    insert_prefix = (
        "insert into public.state_legislators_current (\n  "
        + ", ".join(columns)
        + "\n)\nvalues\n"
    )

    body: list[str] = []
    for batch in chunked(rows, args.chunk_size):
        tuples: list[str] = []
        for row in batch:
            values = [
                row["legislator_key"],
                row["source_person_id"],
                row["seat_key"],
                row["state"],
                row["chamber"],
                row["district"],
                row["name"],
                row["title"],
                row["party"],
                row["website"],
                row["phone"],
                row["source_file"],
                row["source_snapshot_url"],
                row["source_snapshot_as_of"],
            ]
            literals = [sql_literal(value) for value in values]
            tuples.append("  (" + ", ".join(literals + ["now()", "now()"]) + ")")

        body.append(insert_prefix + ",\n".join(tuples) + ";\n")

    footer = [
        "commit;",
        "",
        "-- Verification",
        "select state, count(*) as legislators",
        "from public.state_legislators_current",
        f"where state in ({quoted_states})",
        "group by state",
        "order by state;",
        "",
    ]

    sql_text = "\n".join(header) + "\n".join(body) + "\n".join(footer)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(sql_text, encoding="utf-8")

    print(f"Wrote SQL: {args.output}")
    print(f"Rows: {len(rows)}")
    print(f"States: {', '.join(states_list)}")


if __name__ == "__main__":
    main()
