#!/usr/bin/env tsx
/**
 * generate-baseline-report.ts
 *
 * Reads `data-ops/derived/qc_category_mapping.yaml` and writes
 * `data-ops/derived/civica_historical_baseline.md` — the founder-facing
 * historical-baseline pitch artifact, regenerated on every change.
 *
 * Run:
 *   pnpm data:report:baseline
 */
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { parse as parseYaml } from "yaml";

const ROOT = process.cwd();
const INPUT_YAML = join(ROOT, "data-ops", "derived", "qc_category_mapping.yaml");
const OUTPUT_MD = join(ROOT, "data-ops", "derived", "civica_historical_baseline.md");

interface CivicaControl {
  control_id: string;
  control_description: string;
  evidence_link: string;
  defensibility_impact: string;
}

interface Category {
  cdss_error_category: string;
  element_code: string;
  weighted_count: number;
  share_of_errored_cases_pct: number;
  cfr_basis: string;
  obbba_section: string;
  dollar_attribution_methodology: string;
  civica_controls: CivicaControl[];
  case_examples: string[];
  status: "documented" | "hypothesized" | "refuted";
}

interface Mapping {
  version: number;
  source_publication: string;
  source_pulled_at: string;
  categories: Category[];
}

function fmtPct(n: number): string {
  return `${n.toFixed(2)}%`;
}

function fmtInt(n: number): string {
  return n.toLocaleString("en-US");
}

function buildReport(m: Mapping, now: string): string {
  const total = m.categories.length;
  const documented = m.categories.filter((c) => c.status === "documented");
  const hypothesized = m.categories.filter((c) => c.status === "hypothesized");
  const refuted = m.categories.filter((c) => c.status === "refuted");
  const totalWeightedShare = m.categories.reduce(
    (s, c) => s + c.share_of_errored_cases_pct,
    0,
  );
  const documentedShare = documented.reduce(
    (s, c) => s + c.share_of_errored_cases_pct,
    0,
  );

  const sections: string[] = [];

  // --- Page 1: framing -----------------------------------------------------
  sections.push(
    `# Civica Historical Baseline\n\n` +
      `_Generated ${now} from \`data-ops/derived/qc_category_mapping.yaml\` (schema v${m.version})._\n` +
      `_Underlying ranking source: ${m.source_publication}, pulled ${m.source_pulled_at}._\n\n` +
      `> ⚠️ Do not edit this file by hand. It is regenerated on every change to ` +
      `the YAML mapping. To revise content, edit the YAML and run \`pnpm data:report:baseline\`.\n` +
      `\n---\n`,
  );

  sections.push(
    `## 1 · OBBBA Liability Framing\n\n` +
      `P.L. 119-21 (OBBBA) §10105 takes effect FY2028, converting payment-error ` +
      `rate (PER) into a federally-mandated state cost-share liability:\n\n` +
      `| PER band | State share | Federal share |\n` +
      `|---|---|---|\n` +
      `| < 6% | 0% | 100% |\n` +
      `| 6% to < 8% | 5% | 95% |\n` +
      `| 8% to < 10% | 10% | 90% |\n` +
      `| ≥ 10% | 15% | 85% |\n\n` +
      `Delayed-implementation clause §10105(B)(iii): states whose FY25 PER × 1.5 ` +
      `≥ 20% (i.e. ≥ 13.33%) are pushed to FY2029. This is the cliff documented ` +
      `in \`~/Desktop/Civica USDA data/deliverables/civica_10105_fy29_cliff.pdf\`.\n\n` +
      `**The pitch:** every percentage point of PER above 6% maps to real ` +
      `state-budget dollars starting FY28. The federal QC ELEMENT codes below ` +
      `enumerate what drives error. Each category is a wedge where a Civica ` +
      `control either already exists or names the gap.\n\n---\n`,
  );

  // --- Page 2-5: per-category ---------------------------------------------
  sections.push(`## 2 · Mapping — federal QC ELEMENT codes → Civica controls\n`);

  const sorted = [...m.categories].sort(
    (a, b) => b.share_of_errored_cases_pct - a.share_of_errored_cases_pct,
  );
  for (const c of sorted) {
    const statusBadge =
      c.status === "documented" ? "✅ documented" :
      c.status === "hypothesized" ? "⏳ hypothesized" :
      "🚫 refuted";
    sections.push(`### ${c.cdss_error_category} — ${statusBadge}`);
    sections.push(
      `- **Weighted share of all errored cases (FY23):** ${fmtPct(c.share_of_errored_cases_pct)} ` +
        `(${fmtInt(c.weighted_count)} households).\n` +
        `- **CFR basis:** ${c.cfr_basis}\n` +
        `- **OBBBA section:** ${c.obbba_section}\n` +
        `- **Dollar attribution methodology:** ${c.dollar_attribution_methodology}\n`,
    );

    if (c.civica_controls.length === 0) {
      sections.push(`_No Civica control mapped._\n`);
    } else {
      sections.push(`**Civica controls:**\n`);
      for (const ctrl of c.civica_controls) {
        sections.push(
          `- \`${ctrl.control_id}\` — ${ctrl.control_description} ` +
            `_(${ctrl.defensibility_impact})_  \n  → \`${ctrl.evidence_link}\``,
        );
      }
      sections.push("");
    }

    if (c.case_examples.length > 0) {
      sections.push(`**Case examples:**\n`);
      for (const ex of c.case_examples) {
        sections.push(`- ${ex}`);
      }
      sections.push("");
    }
    sections.push(`---\n`);
  }

  // --- Page 6: coverage summary -------------------------------------------
  sections.push(`## 3 · Coverage Summary\n`);
  sections.push(
    `- **Categories tracked:** ${total}\n` +
      `- **Documented (Civica has a real control):** ${documented.length} / ${total} ` +
      `(${fmtPct((documented.length / total) * 100)})\n` +
      `- **Hypothesized (named gap, no code yet):** ${hypothesized.length} / ${total}\n` +
      `- **Refuted (intentionally out of scope):** ${refuted.length} / ${total}\n` +
      `- **Weighted error share covered:** ${fmtPct(documentedShare)} of ` +
      `${fmtPct(totalWeightedShare)} represented in this mapping\n\n`,
  );

  sections.push(`| Status | ELEMENT | Category | Share of errored cases |\n|---|---|---|---|`);
  for (const c of sorted) {
    const bullet = c.status === "documented" ? "✅" : c.status === "hypothesized" ? "⏳" : "🚫";
    sections.push(
      `| ${bullet} | ${c.element_code} | ${c.cdss_error_category.replace(/^ELEMENT \d+ — /, "")} | ${fmtPct(c.share_of_errored_cases_pct)} |`,
    );
  }
  sections.push("");

  // --- Appendix ------------------------------------------------------------
  sections.push(`---\n\n## Appendix · Raw citations\n`);
  const citations = new Set<string>();
  for (const c of m.categories) {
    for (const part of c.cfr_basis.split(";")) {
      const trimmed = part.trim();
      if (trimmed) citations.add(trimmed);
    }
  }
  for (const cit of [...citations].sort()) {
    sections.push(`- ${cit}`);
  }
  sections.push("");

  sections.push(
    `### Source files\n` +
      `- \`data-ops/derived/qc_category_mapping.yaml\` — canonical mapping\n` +
      `- \`packages/cfr-273/\` — Tier 2 reference rule index (223 rows)\n` +
      `- \`~/Desktop/Civica USDA data/data/qc_profile/qc_fy2023_error_attribution.csv\` — ranking source\n` +
      `- \`~/Desktop/Civica USDA data/analysis/qc_fy2023_profile.md\` — methodology + headline findings\n` +
      `- \`~/Desktop/Civica USDA data/deliverables/civica_10105_fy29_cliff.pdf\` — §10105 framing\n`,
  );

  return sections.join("\n");
}

async function main() {
  const yamlText = await readFile(INPUT_YAML, "utf8");
  const mapping = parseYaml(yamlText) as Mapping;
  const now = new Date().toISOString().slice(0, 10);
  const report = buildReport(mapping, now);
  await writeFile(OUTPUT_MD, report);
  console.log(`wrote ${OUTPUT_MD} (${report.length} bytes)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
