-- GovHelp abuse protection: per-user and per-IP sliding-window limiter.

create table if not exists public.govhelp_rate_limits (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  ip_address inet,
  request_at timestamptz not null default now()
);

create index if not exists idx_govhelp_rate_limits_user_request_at
  on public.govhelp_rate_limits (user_id, request_at desc);

create index if not exists idx_govhelp_rate_limits_ip_request_at
  on public.govhelp_rate_limits (ip_address, request_at desc)
  where ip_address is not null;

alter table public.govhelp_rate_limits enable row level security;

revoke all on public.govhelp_rate_limits from anon;
revoke all on public.govhelp_rate_limits from authenticated;

create or replace function public.consume_govhelp_rate_limit(
  p_user_id uuid,
  p_ip inet default null,
  p_user_limit integer default 20,
  p_ip_limit integer default 60,
  p_window_seconds integer default 3600
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := now();
  v_window interval := make_interval(secs => greatest(60, coalesce(p_window_seconds, 3600)));
  v_user_count integer := 0;
  v_ip_count integer := 0;
  v_retry_after integer := 0;
begin
  if p_user_id is null then
    return jsonb_build_object('allowed', false, 'retry_after_seconds', 60);
  end if;

  delete from public.govhelp_rate_limits
  where request_at < (v_now - v_window);

  select count(*)
    into v_user_count
  from public.govhelp_rate_limits
  where user_id = p_user_id
    and request_at >= (v_now - v_window);

  if p_ip is not null then
    select count(*)
      into v_ip_count
    from public.govhelp_rate_limits
    where ip_address = p_ip
      and request_at >= (v_now - v_window);
  end if;

  if v_user_count >= greatest(1, coalesce(p_user_limit, 20))
     or (p_ip is not null and v_ip_count >= greatest(1, coalesce(p_ip_limit, 60))) then
    with over_limit as (
      select request_at + v_window as release_at
      from public.govhelp_rate_limits
      where (user_id = p_user_id and request_at >= (v_now - v_window))
         or (p_ip is not null and ip_address = p_ip and request_at >= (v_now - v_window))
      order by request_at asc
      limit 1
    )
    select greatest(1, ceil(extract(epoch from (release_at - v_now)))::integer)
      into v_retry_after
    from over_limit;

    if v_retry_after is null then
      v_retry_after := greatest(1, coalesce(p_window_seconds, 3600));
    end if;

    return jsonb_build_object('allowed', false, 'retry_after_seconds', v_retry_after);
  end if;

  insert into public.govhelp_rate_limits (user_id, ip_address, request_at)
  values (p_user_id, p_ip, v_now);

  return jsonb_build_object('allowed', true, 'retry_after_seconds', 0);
end;
$$;

revoke all on function public.consume_govhelp_rate_limit(uuid, inet, integer, integer, integer) from public;
revoke all on function public.consume_govhelp_rate_limit(uuid, inet, integer, integer, integer) from anon;
revoke all on function public.consume_govhelp_rate_limit(uuid, inet, integer, integer, integer) from authenticated;
grant execute on function public.consume_govhelp_rate_limit(uuid, inet, integer, integer, integer) to service_role;
