-- regops — Parsed-payload snapshots from successful source fetches (E2).
--
-- Source design: docs/designs/regops-engine.md §"Snapshot vs. audit log".
-- Sibling of regops.source_audit_log (20260593): the audit log captures
-- EVERY fetch attempt (success and failure), while this table captures
-- only the PARSED PAYLOAD of successful fetches — the actual document
-- list / COLA values / rule summaries the adapter returned. Two tables,
-- two purposes:
--
--   audit_log = "what did we fetch, when, with what outcome"
--               → answers a regulator's chain-of-custody question
--               → body_ref points to raw bytes in blob storage
--
--   snapshots = "here is the parsed data the source returned"
--               → answers "what did source X look like at time T"
--               → data is inline jsonb (small structured payloads)
--
-- The orchestrator (packages/regops-engine/src/polling/orchestrator.ts)
-- only writes to snapshots on FetchResult.kind === "Success". NoChange,
-- TransientFailure, StructuralFailure, SourceWedged all flow to the
-- audit log only.
--
-- Append-only via trigger, same posture as source_audit_log: every
-- snapshot is a historical state we may need to demonstrate later.
-- A regulator asking "what did the COLA index page look like on
-- May 15" deserves a definitive answer, not a git-history reconstruction.
--
-- RLS mirrors source_audit_log: service_role full access, plus a
-- domain-scoped counsel read using the helpers from 20260594
-- (is_active_counsel_for + source_id_to_domain). Adding a new source
-- adapter requires updating source_id_to_domain in the policy of the
-- audit_log migration before counsel can see the new snapshots.

-- ---------------------------------------------------------------------------
-- 1. snapshots — parsed payload, one row per Success outcome
-- ---------------------------------------------------------------------------

create table if not exists regops.snapshots (
  snapshot_id      uuid        primary key default snap_enrollment.gen_uuidv7(),

  -- Source adapter identifier. Same constraint as source_audit_log.source_id
  -- so a (snapshots ⋈ source_audit_log) join on source_id is well-typed.
  source_id        text        not null
    check (source_id ~ '^[a-z0-9][a-z0-9-]{2,63}$'),

  -- Adapter's declared domain — "eligibility", "calculation", "compliance",
  -- etc. Loosely constrained here; the canonical enum lives in code
  -- (packages/regops-engine/src/sources/types.ts DomainTag). Drift between
  -- code + db is caught by the adapter-side tests, not by a SQL enum,
  -- because the domain tag set evolves as we add new sources and a SQL
  -- enum migration per new tag is overhead.
  domain_tag       text        not null
    check (length(domain_tag) between 1 and 64),

  -- Wall-clock time the SOURCE was fetched (passed in by the adapter,
  -- not generated by the db). Distinct from recorded_at below.
  fetched_at       timestamptz not null,

  -- Content hash of the fetched payload (SHA-256). Always non-empty
  -- on snapshots (NoChange + failures never reach this table; only
  -- Success outcomes, which always have a hash). Joinable to
  -- source_audit_log.url_hash for the (snapshot ⋈ audit) trail.
  url_hash         text        not null
    check (length(url_hash) between 1 and 128),

  -- Parsed payload from the adapter. Shape is adapter-specific; each
  -- adapter documents its own. Examples:
  --   federal-register-snap  → array of FederalRegisterDocument objects
  --   usda-fns-cola          → object {effective_date, household_size_to_max}
  -- Kept as jsonb (not jsonb[]) so adapters that return a single object
  -- vs. an array stay flexible.
  data             jsonb       not null,

  -- Time we WROTE the row. Differs from fetched_at by however long the
  -- write took. Defaults to clock_timestamp() so concurrent inserts get
  -- distinct timestamps for ordering.
  recorded_at      timestamptz not null default clock_timestamp()
);

comment on table regops.snapshots is
  'Parsed payload from successful SourceAdapter.fetchOnce() outcomes. '
  'Append-only via trigger. Sibling of regops.source_audit_log: audit '
  'captures every fetch (incl. failures); snapshots capture only Success '
  'with the parsed result data. See docs/designs/regops-engine.md.';

comment on column regops.snapshots.fetched_at is
  'Time the source was polled, set by the adapter. Differs from '
  'recorded_at (db-side write time) by network + serialization latency.';

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

-- Primary query pattern: "give me the most recent snapshot for source X"
-- → driven by the dashboard's source-detail view + the orchestrator's
-- supersession-detection follow-up.
create index snapshots_source_fetched_idx
  on regops.snapshots (source_id, fetched_at desc);

-- Dedup / "have we seen this content already" lookup. Not unique because
-- the same hash CAN reappear if a source flips back to a prior state
-- (e.g., USDA pulls a memo then reposts the same one) — we want both
-- snapshots, not a constraint violation.
create index snapshots_source_urlhash_idx
  on regops.snapshots (source_id, url_hash);

-- ---------------------------------------------------------------------------
-- Immutability — trigger denies UPDATE, DELETE, TRUNCATE for ALL roles
-- ---------------------------------------------------------------------------
--
-- Same defense-in-depth posture as source_audit_log: service_role
-- bypasses RLS but NOT triggers. Combined with the RLS policies below,
-- this is a true append-only table.

create or replace function regops.snapshots_block_mutation()
  returns trigger
  language plpgsql
  as $$
begin
  raise exception
    'regops.snapshots is append-only. % is not permitted. '
    'If you genuinely need to alter snapshot history (e.g., redact PII '
    'under legal obligation), do so via a documented operational '
    'procedure that drops and recreates this trigger.',
    tg_op;
end;
$$;

create trigger snapshots_block_update
  before update on regops.snapshots
  for each row execute function regops.snapshots_block_mutation();

create trigger snapshots_block_delete
  before delete on regops.snapshots
  for each row execute function regops.snapshots_block_mutation();

create trigger snapshots_block_truncate
  before truncate on regops.snapshots
  for each statement execute function regops.snapshots_block_mutation();

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
--
-- service_role can INSERT and SELECT. Counsel reviewers get SELECT
-- scoped to their assigned domain, mirroring the audit-log policy in
-- 20260594. Both policies use the helpers from that migration:
--   regops.is_active_counsel_for(uuid, regops.counsel_domain)
--   regops.source_id_to_domain(text)
-- Updating source_id_to_domain to map a new adapter is a one-place
-- change that unlocks counsel visibility for both audit_log + snapshots.

alter table regops.snapshots enable row level security;

create policy snapshots_service_role_all
  on regops.snapshots
  for all to service_role using (true) with check (true);

create policy snapshots_counsel_domain_read
  on regops.snapshots
  for select to authenticated
  using (
    regops.is_active_counsel_for(
      auth.uid(),
      regops.source_id_to_domain(source_id)
    )
  );

-- ---------------------------------------------------------------------------
-- Grants
-- ---------------------------------------------------------------------------
--
-- USAGE on the regops schema was granted in 20260594 (to authenticated +
-- service_role). We only need the table-level SELECT here.

grant select on regops.snapshots to authenticated;
